apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: surfersweb
  #namespace: default
  description: Surf Condition Web Reporter and Cams
  tags:
    - app-accelerator
    - python
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=surferslookout,component=frontend'
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: group:surfers-crew
  system: surfers-system
  dependsOn:
    - component:surferslookout-db
    - component:surfersapi
  consumesApis:
    - surfersapi-tap2.tanzu.rocks
  