---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: surfers-system
  #namespace: default
  description: Surfers Lookout Web System
spec:
  owner: group:surfers-crew
  domain: surfers-domain

---


apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bigbank-system
  #namespace: default
  description: The Big Bank CC System
spec:
  owner: group:banking-crew
  domain: bigbank-domain

---


apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: kyc-system
  #namespace: default
  description: The Big Bank KYC System
spec:
  owner: group:banking-crew
  domain: bigbank-domain

