
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kyc
  #namespace: default
  description: Big Bank KYC Component
  tags:
    - app-accelerator
    - python
    - web
    - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=bigbank,component=frontend'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:bankers-crew
  system: bigbank-system
