
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: surfers-root
  #namespace: default
  description: Overall organisation parent group
spec:
  type: root
  profile:
    displayName: Surfer Top Level Group
  children: [surfers-crew]

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: surfers-crew
  #namespace: default
  description: Team focused on the Surfer system
spec:
  type: team
  profile:
    displayName: Surfer Crew
  parent: surfers-org
  children: []

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: surfer-a
  namespace: default
spec:
  profile:
    displayName: Surfer Dude A
  memberOf: [surfers-crew]


---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: surfer-b
  namespace: default
spec:
  profile:
    displayName: Surfer Dude B
  memberOf: [surfers-crew]

---


---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: banking-head
  #namespace: default
  description: Overall organisation parent group
spec:
  type: root
  profile:
    displayName: Bankers Top Level Group
  children: [banking-crew]

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: banking-crew
  #namespace: default
  description: Team focused on the Banking system
spec:
  type: team
  profile:
    displayName: Banker Crew
  parent: bigbank-org
  children: []

---


apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: banker-a
  namespace: default
spec:
  profile:
    displayName: Banker Member A
  memberOf: [banking-crew]