

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: banking-head
  #namespace: default
  description: Overall organisation parent group
spec:
  type: root
  profile:
    displayName: Bankers Top Level Group
  children: [banking-crew]

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: banking-crew
  #namespace: default
  description: Team focused on the Banking system
spec:
  type: team
  profile:
    displayName: Banker Crew
  parent: bigbank-org
  children: []

---


apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: banker-a
  namespace: default
spec:
  profile:
    displayName: Banker Member A
  memberOf: [banking-crew]